import React from "react"
import { Jumbotron, Image } from "react-bootstrap"
import Meta from "../components/Meta"
import FormContainer from "../components/FormContainer"
import { appname } from "../constants/commonConstants"

const AboutScreen = () => {
  return (
    <Jumbotron>
      <Meta title={`About | ${appname}`} />
      <FormContainer>
        <h2>О моем магазине</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quasi et cupiditate enim impedit delectus sed deleniti deserunt assumenda, cum illo dolor quas optio vel quidem ex consectetur tenetur corrupti? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit vitae nemo dolorum doloremque, odio minus obcaecati recusandae, non porro assumenda inventore temporibus veniam aperiam quas expedita quia mollitia excepturi totam architecto earum laborum! Reprehenderit eum suscipit deleniti, ipsa eveniet sapiente odit laboriosam itaque quibusdam nulla esse error dignissimos obcaecati laudantium exercitationem aliquid tempora sit dolorum odio. Dolor, facere minima aperiam voluptates id sed similique ex ab voluptatem, earum repellendus. Nisi porro incidunt consequatur ipsa molestias, neque repudiandae. Quod repellendus earum aspernatur libero fugiat minus dolorum amet corporis molestiae voluptas? Ipsum corporis cumque excepturi molestiae officia perspiciatis qui odit impedit nulla!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit nihil explicabo perspiciatis similique magnam sit numquam voluptatem quibusdam atque! Esse eveniet provident, numquam velit obcaecati perferendis fugiat accusamus aperiam ducimus tempore doloribus quas dolores quia? Sed voluptas, delectus, iure reiciendis magni nesciunt temporibus tempora commodi, exercitationem illo debitis amet accusantium eius minus officia voluptate corporis obcaecati ipsa? Ullam quia alias accusamus ut dicta veniam dolorem, sit iste consectetur aperiam, deserunt dolorum id maiores quidem labore recusandae ad hic cupiditate? Pariatur tenetur ducimus ab et excepturi illum vitae, perspiciatis, consequuntur corporis voluptas est illo quam doloremque impedit, praesentium dicta repudiandae maxime. Magnam, animi! Fuga dolorem harum, dolorum iusto quod impedit ut voluptatem veniam at ad iste obcaecati. Fuga hic nihil exercitationem maxime esse pariatur? Atque modi tenetur aut distinctio recusandae ratione porro! Perferendis nemo et voluptatem veritatis, recusandae tenetur sequi accusantium explicabo libero eius temporibus, quas vitae ex qui delectus voluptatibus blanditiis accusamus pariatur numquam voluptas harum fuga dignissimos commodi minus. Consequatur beatae odit dolorem sapiente numquam voluptatibus, veniam, voluptatem pariatur fuga quaerat corrupti fugiat nihil architecto doloremque dolore ea explicabo quis. Distinctio sequi perferendis praesentium expedita id quis vero inventore itaque cumque? Quo laborum velit rem, at impedit repudiandae optio!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A nam non provident ratione quibusdam eligendi quo incidunt adipisci maxime aliquam corrupti blanditiis consectetur omnis, amet, ut voluptas animi pariatur possimus ab quisquam ad? Delectus deserunt, laborum enim expedita, commodi officia fuga quod modi quibusdam a, ut qui saepe iure voluptatum minima fugit cumque veritatis! Delectus doloribus asperiores quia reiciendis esse corporis officia laudantium nihil dolor? Impedit nobis iusto recusandae perferendis ab libero neque nesciunt cumque quas optio in at soluta, officia rerum consequatur expedita, ad minima. Perspiciatis quisquam dicta tempore nostrum blanditiis in earum, non omnis sequi dolores, sed atque! Ut iste perspiciatis exercitationem ab earum. Minus dolores maiores ipsa quis, odit unde, necessitatibus fugiat delectus, ut consequatur inventore sed recusandae. Ullam cupiditate sunt magni, quibusdam facilis minima ut harum aliquam eligendi consequuntur corporis dolore dolorum voluptas animi vero aut enim tempore, reiciendis et a illum? Asperiores laudantium cum beatae ipsa, id omnis at nobis est sapiente sequi dolore excepturi dignissimos blanditiis maiores nam perspiciatis optio aliquid tempore cumque vel magnam expedita natus! Consectetur ea quidem, obcaecati quod nesciunt exercitationem dolores accusamus reiciendis minus praesentium, repudiandae alias! Laborum fugiat quis ea dolores doloremque, reiciendis laboriosam obcaecati veniam repellat illum ratione deserunt, labore eius dicta ad consequatur aperiam nihil est qui aut velit nemo. Tempore doloribus, et at magni ex saepe eum quibusdam nesciunt a voluptatem asperiores fugit nulla magnam, impedit possimus esse nam suscipit provident architecto rerum quisquam voluptatum dolores! Reiciendis corrupti, obcaecati, id suscipit saepe laudantium, sit non recusandae veniam ipsum tempore! Quae eaque voluptate ab id ratione in, magnam officia iusto adipisci consectetur sint hic voluptatibus minima totam quisquam eveniet dolore aperiam? Nihil et odit at obcaecati minus ratione, consequatur, necessitatibus odio rerum eius eos veniam dolores itaque! Itaque voluptatum quae iusto accusamus eum temporibus earum adipisci magnam?</p>
      </FormContainer>
    </Jumbotron>
  )
}

export default AboutScreen
